# lab5_1 代码部分


库导入

In [93]:
import numpy as np
import sympy as sp
import matplotlib.pylab as plt
import math

定义高斯列主元消除函数

In [95]:
def GuassP(A,b)->np.ndarray:
    
    r=len(A)
    c=len(A[0])

    # 如果输入的是习惯的np.array，则转为list进行计算，因为最后结果会有一点不一样
    if isinstance(A,np.ndarray): 
        A=A.tolist()
    if isinstance(b,np.ndarray):
        b=b.flatten().tolist()
    print("原系数矩阵：",np.matrix(A))
    print("原右端项：",b)
    # 开始消元
    for k in range(r-1):
        max_n=abs(A[k][k])
        max_i=k
        for i in range(k+1,r):
            if abs(A[i][k])>max_n:
                max_n=abs(A[i][k])
                max_i=i
        if max == 0:
            print("系数矩阵为奇异矩阵，无解")
            return False,[]
        # 交换行
        if max_i != k:
            A[k],A[max_i]=A[max_i],A[k]
            b[k],b[max_i]=b[max_i],b[k]
        
        for i in range(k+1,r):
            m=A[i][k]/A[k][k]
            for j in range(k,c):
                A[i][j]=A[i][j]-m*A[k][j]
            b[i]=b[i]-m*b[k]
    print("消元后系数矩阵：",np.matrix(A))
    print("消元后右端项：",b)
    if A[r-1][c-1]==0:
        print("系数矩阵为奇异矩阵，无解")
        return False,[]

    # 初始化返回答案矩阵
    ans=np.zeros(r)
    # 开始回代求解
    for i in range(r-1,-1,-1):
        ans[i]=b[i]
        for j in range(i+1,r):
            ans[i]=ans[i]-A[i][j]*ans[j]
        ans[i]=ans[i]/A[i][i]
    print("回代求解后的结果：",ans)
    return True,ans


### 问题一：

(1):


In [96]:
A=[[0.4096,0.1234,0.3678,0.2943],[0.2246,0.3872,0.4015,0.1129],[0.3645,0.1920,0.3781,0.0643],[0.1784,0.4002,0.2786,0.3927]]
b=[1.1951,1.1262,0.9989,1.2499]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

    

原系数矩阵： [[0.4096 0.1234 0.3678 0.2943]
 [0.2246 0.3872 0.4015 0.1129]
 [0.3645 0.192  0.3781 0.0643]
 [0.1784 0.4002 0.2786 0.3927]]
原右端项： [1.1951, 1.1262, 0.9989, 1.2499]
消元后系数矩阵： [[ 4.09600000e-01  1.23400000e-01  3.67800000e-01  2.94300000e-01]
 [ 0.00000000e+00  3.46453516e-01  1.18405859e-01  2.64518555e-01]
 [-2.77555756e-17  0.00000000e+00  9.06146128e-02 -2.92442479e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.87057257e-01]]
消元后右端项： [1.1951, 0.7293779296875, -0.2018278661797387, -0.18705725686919192]
回代求解后的结果： [1. 1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0, 1.0]


In [98]:
A=[[136.01,90.860,0,0],
[90.860,98.810,-67.590,0],
[0,-67.590,132.01,46.260],
[0,0,46.26,177.17]]
b=[226.87,122.08,110.68,223.43]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

    

原系数矩阵： [[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]
原右端项： [226.87, 122.08, 110.68, 223.43]
消元后系数矩阵： [[ 1.36010000e+02  9.08600000e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -6.75900000e+01  1.32010000e+02  4.62600000e+01]
 [ 0.00000000e+00  0.00000000e+00  4.62600000e+01  1.77170000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.36479429e-01]]
消元后右端项： [226.87, 110.68, 223.43, -0.13647942935829604]
回代求解后的结果： [1. 1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0, 1.0]


(2)

In [97]:
A=[[136.01,90.860,0,0],
[90.860,98.810,-67.590,0],
[0,-67.590,132.01,46.260],
[0,0,46.26,177.17]]
b=[226.87,122.08,110.68,223.43]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

    

原系数矩阵： [[136.01  90.86   0.     0.  ]
 [ 90.86  98.81 -67.59   0.  ]
 [  0.   -67.59 132.01  46.26]
 [  0.     0.    46.26 177.17]]
原右端项： [226.87, 122.08, 110.68, 223.43]
消元后系数矩阵： [[ 1.36010000e+02  9.08600000e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -6.75900000e+01  1.32010000e+02  4.62600000e+01]
 [ 0.00000000e+00  0.00000000e+00  4.62600000e+01  1.77170000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.36479429e-01]]
消元后右端项： [226.87, 110.68, 223.43, -0.13647942935829604]
回代求解后的结果： [1. 1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0, 1.0]


(3)

In [99]:
A=[[1,1/2,1/3,1/4],
[1/2,1/3,1/4,1/5],
[1/3,1/4,1/5,1/6],
[1/4,1/5,1/6,1/7]]
b=[25/12,77/60,57/60,319/420]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

    

原系数矩阵： [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
原右端项： [2.0833333333333335, 1.2833333333333334, 0.95, 0.7595238095238095]
消元后系数矩阵： [[ 1.00000000e+00  5.00000000e-01  3.33333333e-01  2.50000000e-01]
 [ 0.00000000e+00  8.33333333e-02  8.88888889e-02  8.33333333e-02]
 [ 0.00000000e+00  0.00000000e+00 -5.55555556e-03 -8.33333333e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  3.57142857e-04]]
消元后右端项： [2.0833333333333335, 0.25555555555555554, -0.013888888888888729, 0.0003571428571429204]
回代求解后的结果： [1. 1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0, 1.0]


(4)

In [100]:
A=[[10,7,8,7],
[7,5,6,5],
[8,6,10,9],
[7,5,9,10]]
b=[32,23,33,31]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

原系数矩阵： [[10  7  8  7]
 [ 7  5  6  5]
 [ 8  6 10  9]
 [ 7  5  9 10]]
原右端项： [32, 23, 33, 31]
消元后系数矩阵： [[10.    7.    8.    7.  ]
 [ 0.    0.4   3.6   3.4 ]
 [ 0.    0.    2.5   4.25]
 [ 0.    0.    0.    0.1 ]]
消元后右端项： [32, 7.399999999999999, 6.749999999999989, 0.1000000000000052]
回代求解后的结果： [1. 1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0, 1.0]
