# lab5_5 代码部分


库导入

In [1]:
import numpy as np
import sympy as sp
import matplotlib.pylab as plt
import math

定义高斯列主元消除函数

In [2]:
def GuassP(A,b)->np.ndarray:
    
    r=len(A)
    c=len(A[0])

    # 如果输入的是习惯的np.array，则转为list进行计算，因为最后结果会有一点不一样
    if isinstance(A,np.ndarray): 
        A=A.tolist()
    if isinstance(b,np.ndarray):
        b=b.flatten().tolist()
    print("原系数矩阵：",np.matrix(A))
    print("原右端项：",b)
    # 开始消元
    for k in range(r-1):
        max_n=abs(A[k][k])
        max_i=k
        for i in range(k+1,r):
            if abs(A[i][k])>max_n:
                max_n=abs(A[i][k])
                max_i=i
        if max == 0:
            print("系数矩阵为奇异矩阵，无解")
            return False,[]
        # 交换行
        if max_i != k:
            A[k],A[max_i]=A[max_i],A[k]
            b[k],b[max_i]=b[max_i],b[k]
        
        for i in range(k+1,r):
            m=A[i][k]/A[k][k]
            for j in range(k,c):
                A[i][j]=A[i][j]-m*A[k][j]
            b[i]=b[i]-m*b[k]
    print("消元后系数矩阵：",np.matrix(A))
    print("消元后右端项：",b)
    if A[r-1][c-1]==0:
        print("系数矩阵为奇异矩阵，无解")
        return False,[]

    # 初始化返回答案矩阵
    ans=np.zeros(r)
    # 开始回代求解
    for i in range(r-1,-1,-1):
        ans[i]=b[i]
        for j in range(i+1,r):
            ans[i]=ans[i]-A[i][j]*ans[j]
        ans[i]=ans[i]/A[i][i]
    print("回代求解后的结果：",ans)
    return True,ans


### 问题二：

(1):


In [3]:
A=[[197,305,-206,-804],
[46.8,71.3,-47.4,52],
[88.6,76.4,-10.8,802],
[1.45,5.9,6.13,36.5]]
b=[136,11.7,25.1,6.60]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

    

原系数矩阵： [[ 197.    305.   -206.   -804.  ]
 [  46.8    71.3   -47.4    52.  ]
 [  88.6    76.4   -10.8   802.  ]
 [   1.45    5.9     6.13   36.5 ]]
原右端项： [136, 11.7, 25.1, 6.6]
消元后系数矩阵： [[ 197.          305.         -206.         -804.        ]
 [   0.          -60.77258883   81.84771574 1163.59593909]
 [   0.            0.           12.56885167  112.40049782]
 [   0.            0.            0.          221.02959897]]
消元后右端项： [136, -36.065482233502536, 3.4298804730960057, -19.916647727756796]
回代求解后的结果： [ 0.95367911  0.32095685  1.07870808 -0.09010851]
解为(保留四位小数): [0.9537, 0.321, 1.0787, -0.0901]


(2)

In [4]:
A=[[0.5398,0.7161,-0.5554,-0.2982],
[0.5257,0.6924,0.3565,-0.6255],
[0.6465,-0.8187,-0.1872,0.1291],
[0.5814,0.94,-0.7779,-0.4042]]
b=[0.2058,-0.0503,0.1070,0.1859]
jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])

    

原系数矩阵： [[ 0.5398  0.7161 -0.5554 -0.2982]
 [ 0.5257  0.6924  0.3565 -0.6255]
 [ 0.6465 -0.8187 -0.1872  0.1291]
 [ 0.5814  0.94   -0.7779 -0.4042]]
原右端项： [0.2058, -0.0503, 0.107, 0.1859]
消元后系数矩阵： [[ 0.6465     -0.8187     -0.1872      0.1291    ]
 [ 0.          1.67626014 -0.6095503  -0.52030014]
 [ 0.          0.          1.00258548 -0.30892459]
 [ 0.          0.          0.          0.06231529]]
消元后右端项： [0.107, 0.08967447795823666, -0.20996203473079655, 0.06459224565073099]
回代求解后的结果： [0.5161773  0.41521947 0.1099661  1.03653922]
解为(保留四位小数): [0.5162, 0.4152, 0.11, 1.0365]


(3)

In [5]:
A=[[10,1,2],[1,10,2],[1,1,5]]
b=[13,13,7]

jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])


原系数矩阵： [[10  1  2]
 [ 1 10  2]
 [ 1  1  5]]
原右端项： [13, 13, 7]
消元后系数矩阵： [[10.          1.          2.        ]
 [ 0.          9.9         1.8       ]
 [ 0.          0.          4.63636364]]
消元后右端项： [13, 11.7, 4.636363636363637]
回代求解后的结果： [1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0]


(4)

In [6]:
A=[[4,-2,-4],[-2,17,10],[-4,10,9]]
b=[-2,25,15]

jud,ans1_1=GuassP(A,b)
if jud:
    print("解为(保留四位小数):",[round(a,4) for a in ans1_1])


原系数矩阵： [[ 4 -2 -4]
 [-2 17 10]
 [-4 10  9]]
原右端项： [-2, 25, 15]
消元后系数矩阵： [[ 4. -2. -4.]
 [ 0. 16.  8.]
 [ 0.  0.  1.]]
消元后右端项： [-2, 24.0, 1.0]
回代求解后的结果： [1. 1. 1.]
解为(保留四位小数): [1.0, 1.0, 1.0]
