# lab2_1 代码部分


库导入

In [11]:
import math
import numpy as np
import sympy as sp

定义关键Romberg积分法函数

In [12]:
def Romberg(a,b,f,e,n):
    mat = np.zeros((n,n))
    h=(b-a)
    mat[0,0] = h/2*(f.evalf(subs={'x':a})+f.evalf(subs={'x':b}))
    for i in range(1,n):
        
        # 先算出第一行最右端新元素（新内二分的结果）
        sum=0

        for j in range(0,2**(i-1)):
            sum=sum+f.evalf(subs={'x':a+(j+1/2)*h})
        
        mat[0,i]=mat[0,i-1]/2+sum*h/2

        # 然后在利用T-数阵已有结果外推

        for j in range(1,i+1):
            mat[j,i-j]=(mat[j-1,i-j+1]*4**j-mat[j-1,i-j])/(4**j-1)
        

        # 判断是否结束
        if abs(mat[i,0]-mat[i-1,0])<e:
            print("结束：")
            print("T矩阵为:")
            print(mat[0:i+1,0:i+1])
            return True,mat[i,0]
        
        h=h/2
        
    print("停机")
    return False,mat[n-1,0]


### 1.1

$$
\int_0^1{e^xx^2}dx \quad 
\varepsilon =10^{-6}


$$


In [13]:

# 定义函数和精度
x=sp.symbols('x')
exp1 = sp.exp(x)*x**2
e=1e-6

# 调用函数
bo,ans=Romberg(0,1,exp1,e,20)

if(bo):
    print("结果为：",ans)
    print("保留四位小数：",round(ans,4))
# 验证
ss=sp.integrate(exp1,(x,0,1))

print("验证误差为：",abs(ss.evalf()-ans))

结束：
T矩阵为:
[[1.35914091 0.88566062 0.76059633 0.72889018 0.72093578]
 [0.72783385 0.71890824 0.71832146 0.71828431 0.        ]
 [0.7183132  0.71828234 0.71828184 0.         0.        ]
 [0.71828185 0.71828183 0.         0.         0.        ]
 [0.71828183 0.         0.         0.         0.        ]]
结果为： 0.7182818284623739
保留四位小数： 0.7183
验证误差为： 3.32867067243114e-12


1.2
$$
\,\,\int_1^3{e^x\sin xdx} \quad 
\varepsilon =10^{-6}
$$



In [14]:
# 定义函数和精度
x=sp.symbols('x')
exp2 = sp.exp(x)*sp.sin(x)
e=1e-6

# 调用函数
bo,ans=Romberg(1,3,exp2,e,20)

if(bo):
    print("结果为：",ans)
    print("保留四位小数：",round(ans,4))
# 验证
ss=sp.integrate(exp2,(x,1,3))

print("验证误差为：",abs(ss.evalf()-ans))

结束：
T矩阵为:
[[ 5.12182642  9.27976291 10.52055428 10.84204347 10.92309389 10.94339842]
 [10.66574174 10.93415141 10.94920653 10.9501107  10.9501666   0.        ]
 [10.95204539 10.9502102  10.95017097 10.95017033  0.          0.        ]
 [10.95018107 10.95017035 10.95017031  0.          0.          0.        ]
 [10.95017031 10.95017031  0.          0.          0.          0.        ]
 [10.95017031  0.          0.          0.          0.          0.        ]]
结果为： 10.950170314683838
保留四位小数： 10.9502
验证误差为： 1.68043357007264e-12


1.3
$$
\,\,\int_0^1{\frac{4}{1+x^2}dx} 
\quad 
\varepsilon =10^{-6}
$$


In [15]:
# 定义函数和精度
x=sp.symbols('x')
exp3 = 4/(1+x**2)
e=1e-6

# 调用函数
bo,ans=Romberg(0,1,exp3,e,20)

if(bo):
    print("结果为：",ans)
    print("保留四位小数：",round(ans,4))
# 验证
ss=sp.integrate(exp3,(x,0,1))

print("验证误差为：",abs(ss.evalf()-ans))

结束：
T矩阵为:
[[3.         3.1        3.13117647 3.13898849 3.14094161 3.14142989]
 [3.13333333 3.14156863 3.1415925  3.14159265 3.14159265 0.        ]
 [3.14211765 3.14159409 3.14159266 3.14159265 0.         0.        ]
 [3.14158578 3.14159264 3.14159265 0.         0.         0.        ]
 [3.14159267 3.14159265 0.         0.         0.         0.        ]
 [3.14159265 0.         0.         0.         0.         0.        ]]
结果为： 3.141592653638244
保留四位小数： 3.1416
验证误差为： 4.84510209730615e-11


1.4
$$
\,\,\int_0^1{\frac{1}{1+x}dx}
\quad 
\varepsilon =10^{-6}

$$


In [16]:
# 定义函数和精度
x=sp.symbols('x')
exp4 = 1/(1+x)
e=1e-6

# 调用函数
bo,ans=Romberg(0,1,exp4,e,20)

if(bo):
    print("结果为：",ans)
    print("保留四位小数：",round(ans,4))
# 验证
ss=sp.integrate(exp4,(x,0,1))

print("验证误差为：",abs(ss.evalf()-ans))

结束：
T矩阵为:
[[0.75       0.70833333 0.69702381 0.69412185 0.6933912 ]
 [0.69444444 0.69325397 0.69315453 0.69314765 0.        ]
 [0.6931746  0.6931479  0.69314719 0.         0.        ]
 [0.69314748 0.69314718 0.         0.         0.        ]
 [0.69314718 0.         0.         0.         0.        ]]
结果为： 0.6931471819167452
保留四位小数： 0.6931
验证误差为： 1.35679989465842e-9
